<?php
/**
 * Created by Grzegorz Możdżeń <grzegorz.mozdzen@oxm.pl>
 * Date: 17/02/2022
 * Time: 07:48
 */
namespace App\Http\Controllers;

class VoyagerAuthController extends \TCG\Voyager\Http\Controllers\VoyagerAuthController
{
    public function redirectTo()
    {
        $user = $this->guard()->user();
        if ($user) {
            return url('/admin/users/'.$user->id);
        }
        return parent::redirectTo(); // TODO: Change the autogenerated stub
    }
}
